CREATE TABLE Korisnik (
    IdKorisnik INT IDENTITY PRIMARY KEY,
    KorisnickoIme VARCHAR(100) UNIQUE NOT NULL,
    BrojNagrada INT DEFAULT 0
);

CREATE TABLE Film (
    IdFilm INT IDENTITY PRIMARY KEY,
    Naslov VARCHAR(100) NOT NULL,
    Reziser VARCHAR(100) NOT NULL
);

CREATE TABLE Zanr (
    IdZanr INT IDENTITY PRIMARY KEY,
    Naziv VARCHAR(100) NOT NULL
);

CREATE TABLE Tag (
    IdTag INT IDENTITY PRIMARY KEY,
    Naziv VARCHAR(100) NOT NULL
);

CREATE TABLE FilmZanr (
    IdFilm INT NOT NULL,
    IdZanr INT NOT NULL,
    PRIMARY KEY (IdFilm, IdZanr),
    FOREIGN KEY (IdFilm) REFERENCES Film(IdFilm)
        ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (IdZanr) REFERENCES Zanr(IdZanr)
        ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE FilmTag (
    IdFilm INT NOT NULL,
    IdTag INT NOT NULL,
    PRIMARY KEY (IdFilm, IdTag),
    FOREIGN KEY (IdFilm) REFERENCES Film(IdFilm)
        ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (IdTag) REFERENCES Tag(IdTag)
        ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE Ocena (
    IdKorisnik INT NOT NULL,
    IdFilm INT NOT NULL,
    Ocena INT CHECK (Ocena BETWEEN 1 AND 10),
    PRIMARY KEY (IdKorisnik, IdFilm),
    FOREIGN KEY (IdKorisnik) REFERENCES Korisnik(IdKorisnik)
        ON UPDATE CASCADE ON DELETE NO ACTION,
    FOREIGN KEY (IdFilm) REFERENCES Film(IdFilm)
        ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE Watchlist (
    IdKorisnik INT NOT NULL,
    IdFilm INT NOT NULL,
    PRIMARY KEY (IdKorisnik, IdFilm),
    FOREIGN KEY (IdKorisnik) REFERENCES Korisnik(IdKorisnik)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (IdFilm) REFERENCES Film(IdFilm)
        ON UPDATE CASCADE ON DELETE NO ACTION
);